[package]
name = "rust-game-of-life"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.10.1"
warp = "0.2"
config = "0.10"
serde = {version = "1.0", features = ["derive"] }
lazy_static = "1.4"
itertools = "0.10.5"
rand = "0.8.5"
