[default_window_settings]
name = "Game of life"
width = 700.0
height = 700.0
clear_color=[1.0, 1.0, 1.0]

[field_settings]
block_size=20.0
alive_cell_color=[0.7, 0.5, 0.2]
updating_frequency=150 # In milliseconds