[default_window_settings]
name = "Game of life"
width = 700.0
height = 700.0
clear_color=[0.9, 0.9, 0.9]

[field_settings]
block_size=5.0
cell_color_gradient=[[0.5, 0.8, 1.0], [0.1, 0.6, 0.85]]
updating_frequency=80 # In milliseconds

[rule]
survive=[3]
birth=[1,2,3]
health=10